### ISSUE TITLE
Image API not working, ANE not supported on Mac

### ISSUE THREAD

**Issue by demilsson** [logotype/LeapMotionAS3#55]
I'm trying to get the Image API to work, but when running in Socket mode I only get an empty array. I assume I need the ANE to work for the Image API to function?

This brings me to my second problem: when trying to run an app with the ANE, I get the same issue which was posted previously regarding not being supported by MacOS-x86, but rather MacOS-x86-64.

I've tried with the AIR 18 runtime (stable), AIR 19 (beta), AIR 19 - 64 bit (beta, requested from Adobe) - all with the same result. I've also tried the previous version of the ANE - which compiles, but with an empty image array just like with the socket implementation. Perhaps the Image API wasn't added in that version of the ANE?

I'm using Adobe Flash Builder 4.7 to build the app on a Mac running OS X Yosemite. 

I've got access to the cameras using the official Objective-C wrapper so there doesn't appear to be a technical fault with the device.

Is it possible to upload a new ANE which is compatible with the latest GM version of AIR? Or am I doing something else wrong? 

Thanks!

![screen shot 2015-08-25 at 15 52 20](https://cloud.githubusercontent.com/assets/6350121/9468342/6f0eb27a-4b41-11e5-8bf1-2b42657fccff.png)

![screen shot 2015-08-25 at 15 53 00](https://cloud.githubusercontent.com/assets/6350121/9468349/73deb3ae-4b41-11e5-96ce-6bc862624fa1.png)

![screen shot 2015-08-25 at 15 54 06](https://cloud.githubusercontent.com/assets/6350121/9468379/978a0736-4b41-11e5-8ee0-5efb63bb9b8d.png)

**Comment by logotype** [comment]
Hi

Sorry for the trouble. It's correct that Image API only works through the ANE, not via Socket connections.

Regarding 64-bit, the current version on git is built with a early pre-release (January version) of AIR 64-bit. Currently, I'm waiting for Adobe to send the latest build to test again. I'm not sure whether AIR 19 beta includes 64-bit ANE support.

To get Image API to work, you could try this commit (and grab the ane, swc, etc from there), the Image API is included in this version:
https://github.com/logotype/LeapMotionAS3/tree/8f8b406e05c6e07dddb47719cfe1aa68a6bce610

Another reasons why it might not work could be because the LeapMotion drivers has updated. I haven't been able to check with the latest drivers yet (busy at work).

**Comment by logotype** [comment]
@demilsson 8 år sent :D
